name: GitHub actions git informations
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used to get git repository informations
branding:
  icon: feather
  color: gray-dark

runs:
  using: 'docker'
  image: 'ubuntu-latest'
  steps:
    - name: Get Branch Name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: get_branch

    - name: Build and analyze
      if: steps.get_branch.outputs.branch == 'develop'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Package
      run: mvn -B package --file pom.xml -DskipTests

    - name: Get Commit Id
      id: get_commit_id
      run: echo ::set-output name=COMMIT_ID::${GITHUB_SHA::7}

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

    - name: Set TAG Develop
      if: steps.get_branch.outputs.branch == 'develop'
      run: |
        echo "RELEASE_VERSION=${{ steps.get_commit_id.outputs.COMMIT_ID }}" >> $GITHUB_ENV
        echo "GITOPS_BRANCH=develop" >> $GITHUB_ENV

    - name: Set TAG Release
      if: contains(steps.get_branch.outputs.branch, 'tag')
      run: |
        echo "RELEASE_VERSION=${{ steps.vars.outputs.tag }}" >> $GITHUB_ENV
        echo "GITOPS_BRANCH=release" >> $GITHUB_ENV