name: GitHub actions git informations
author: Gabriel Ferreira <gabriel.oliveira@platformbuilders.io>
description: GitHub action used to get git repository informations
branding:
  icon: feather
  color: gray-dark

runs:
  using: "composite"
  steps:
    - name: Get Branch Name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: get_branch

    - name: Get Commit Id
      shell: bash
      run: echo ::set-output name=COMMIT_ID::${GITHUB_SHA::7}
      id: get_commit_id

    - name: Set output
      shell: bash      
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      id: vars